spring.application.name=inventory

spring.datasource.url=jdbc:postgresql://db.mrkqtgxdyyxkyiottzdg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=rbt6vAjAmX30xuuV
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework=DEBUG

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.auth.jwt-secret=${SUPABASE_JWT_SECRET:dev-secret}
supabase.auth.issuer=https://mrkqtgxdyyxkyiottzdg.supabase.co/auth/v1
supabase.auth.audience=authenticated
