ALTER TABLE manufacturers
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE molds
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN manufacturer_id TYPE BIGINT;

ALTER TABLE run_types
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE finishes
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE scales
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE models
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN mold_id TYPE BIGINT,
    ALTER COLUMN run_type_id TYPE BIGINT,
    ALTER COLUMN finish_id TYPE BIGINT,
    ALTER COLUMN scale_id TYPE BIGINT;

ALTER TABLE breed_types
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE breeds
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE colors
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE patterns
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE genders
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE conditions
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE locations
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE horses
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN manufacturer_id TYPE BIGINT,
    ALTER COLUMN mold_id TYPE BIGINT,
    ALTER COLUMN scale_id TYPE BIGINT,
    ALTER COLUMN model_id TYPE BIGINT,
    ALTER COLUMN breed_id TYPE BIGINT,
    ALTER COLUMN breed_type_id TYPE BIGINT,
    ALTER COLUMN color_id TYPE BIGINT,
    ALTER COLUMN pattern_id TYPE BIGINT,
    ALTER COLUMN gender_id TYPE BIGINT,
    ALTER COLUMN condition_id TYPE BIGINT,
    ALTER COLUMN location_id TYPE BIGINT;
